# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: PyPI Yükleyici

concurrency:
  group: PyPIYukleyici
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
    paths:
      - setup.py

jobs:
  PyPIYukleyici:
    name    : PyPI Yükleyici
    runs-on : ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11.8"]

    steps:
      - name : Depo Kontrolü
        uses : actions/checkout@v3

      - name : Python ${{ matrix.python-version }} Sürümü Yükleniyor
        uses : actions/setup-python@v4
        with :
          python-version: ${{ matrix.python-version }}

      - name : Python Sürümünü Göster
        run  : python -c "import sys; print(sys.version)"

      - name : Kütüphaneyi PyPI'ye Yükle
        env  :
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run  : |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          python setup.py bdist_wheel sdist
          twine check dist/*
          python -m twine upload dist/*
          rm -rf build/
          rm -rf dist/
          rm -rf -- *.egg-info/